/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Ananeu.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const modelPath = `${import.meta.env.BASE_URL}meshes/Ananeu.glb`;

export function Model(props) {
  const { nodes, materials } = useGLTF(modelPath)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-0.004, 0, 0]}>
        <mesh geometry={nodes.arterial_VasPrep001.geometry} material={materials.m_skeleton} />
        <mesh geometry={nodes.arterial_VasPrep001_1.geometry} material={materials['m_liver.fullopaque']} />
        <mesh geometry={nodes.arterial_VasPrep001_2.geometry} material={materials['m_hepatic_alt.001']} />
        <mesh geometry={nodes.arterial_VasPrep001_3.geometry} material={materials.m_portal_alt} />
        <mesh geometry={nodes.arterial_VasPrep001_4.geometry} material={materials.m_arterial} />
      </group>
    </group>
  )
}

useGLTF.preload(modelPath)
