/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Metastasen.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const modelPath = `${import.meta.env.BASE_URL}meshes/Metastasen.glb`;

export function Model(props) {
  const { nodes, materials } = useGLTF(modelPath)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-0.01, 0, 0]}>
        <mesh geometry={nodes.metastases_1.geometry} material={materials.m_tumors} />
        <mesh geometry={nodes.metastases_2.geometry} material={materials.m_liver} />
      </group>
    </group>
  )
}

useGLTF.preload(modelPath)
