services:
  - name: livercancer-second-wave-allocator
    type: web
    runtime: node
    plan: starter
    region: frankfurt
    rootDir: allocator-service
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeployTrigger: commit
